# -*- coding: utf-8 -*-
"""Student performance analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTzDDUscB4TaQ5bfIikjAiyDbYOkFYTZ
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(
    page_title="Student Performance Analyzer",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="expanded"
)

# FIXED CSS - removed the syntax error
st.markdown("""
    <style>
    .main {
      padding-top: 2rem;
    }
    .stTabs [data-baseweb="tab-list"]{
      gap:24px;
    }
    .stTabs [data-baseweb="tab"] {
      height:50px;
      padding-left:20px;
      padding-right:20px;
    }
    </style>
""", unsafe_allow_html=True)

def categorize_performance(grade):
    """Categorize student performance into 4 levels"""
    if grade < 10:
        return 'Fail'
    elif grade < 14:
        return 'Pass'
    elif grade < 17:
        return 'Good'
    else:
        return 'Excellent'

@st.cache_data
def load_data():
    """
    load the student performance dataset from UCI repository
    Returns:
        pd.DataFrame:Loaded and preprocessed dataset
    """
    url = "https://raw.githubusercontent.com/arunk13/MSDA-Assignments/master/IS607Fall2015/Assignment3/student-mat.csv"
    df = pd.read_csv(url, sep=';')
    df['average_grade'] = (df['G1'] + df['G2'] + df['G3']) / 3
    df['performance_category'] = df['G3'].apply(categorize_performance)
    return df

def calculate_overall_stats(df):
    """Calculate overall grade statistics"""
    return {
        'mean': df['G3'].mean(),
        'median': df['G3'].median(),
        'std': df['G3'].std(),
        'min': df['G3'].min(),
        'max': df['G3'].max(),
        'pass_rate': (df['G3'] >= 10).sum() / len(df) * 100,
        'fail_rate': (df['G3'] < 10).sum() / len(df) * 100
    }

def analyze_by_category(df, category_col, value_col='G3'):
    """Analyze performance by a specific category"""
    return df.groupby(category_col)[value_col].agg(['mean', 'median', 'count', 'std']).round(2)

def get_correlation_data(df):
    """Get correlation data for key numerical features"""
    numerical_cols = ['age', 'Medu', 'Fedu', 'studytime', 'failures', 'absences', 'G1', 'G2']
    correlations = df[numerical_cols + ['G3']].corr()['G3'].sort_values(ascending=False)
    return correlations

def plot_grade_distribution(df):
    """Create histogram of final grade distribution"""
    fig, ax = plt.subplots()
    ax.hist(df['G3'], bins=20, color='skyblue', edgecolor='black', alpha=0.7)
    ax.axvline(df['G3'].mean(), color='red', linestyle='--', linewidth=2,
               label=f'Mean: {df["G3"].mean():.2f}')
    ax.set_xlabel('Final Grade (G3)', fontsize=12)
    ax.set_ylabel('Number of Students', fontsize=12)
    ax.set_title('Distribution of Final Grades', fontsize=14, fontweight='bold')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)
    return fig

def plot_performance_pie(df):
    """Create pie chart of performance categories"""
    fig, ax = plt.subplots(figsize=(8, 8))
    category_counts = df['performance_category'].value_counts()
    colors = ['#ff6b6b', '#ffd93d', '#6bcf7f', '#4d96ff']
    ax.pie(category_counts, labels=category_counts.index, autopct='%1.1f%%',
           colors=colors, startangle=90, textprops={'fontsize': 11})
    ax.set_title('Performance Category Distribution', fontsize=14, fontweight='bold')
    return fig

def plot_study_time_impact(df):
    """Create bar chart showing study time impact on grades"""
    fig, ax = plt.subplots(figsize=(10, 6))
    study_labels = ['<2h', '2-5h', '5-10h', '>10h']
    study_means = df.groupby('studytime')['G3'].mean()
    bars = ax.bar(study_labels, study_means,
                  color=['#ff6b6b', '#ffd93d', '#6bcf7f', '#4d96ff'],
                  edgecolor='black', alpha=0.8)
    ax.set_xlabel('Weekly Study Time', fontsize=12)
    ax.set_ylabel('Average Final Grade', fontsize=12)
    ax.set_title('Study Time Impact on Performance', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 20)
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
               f'{height:.1f}', ha='center', va='bottom', fontsize=10)
    return fig

def plot_gender_comparison(df):
    """Create bar chart comparing gender performance"""
    fig, ax = plt.subplots(figsize=(8, 6))
    gender_data = df.groupby('sex')['G3'].mean()
    bars = ax.bar(['Female', 'Male'], gender_data,
                  color=['#ff99cc', '#6699ff'],
                  edgecolor='black', alpha=0.8)
    ax.set_ylabel('Average Final Grade', fontsize=12)
    ax.set_title('Gender-Based Performance Comparison', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 20)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
               f'{height:.1f}', ha='center', va='bottom', fontsize=11)
    return fig

def plot_family_support(df):
    """Create bar chart showing family support impact"""
    fig, ax = plt.subplots(figsize=(8, 6))
    support_data = df.groupby('famsup')['G3'].mean()
    bars = ax.bar(['No Support', 'With Support'], support_data,
                  color=['#ff6b6b', '#6bcf7f'], edgecolor='black', alpha=0.8)
    ax.set_ylabel('Average Final Grade', fontsize=12)
    ax.set_title('Family Support Impact on Performance', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 20)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
               f'{height:.1f}', ha='center', va='bottom', fontsize=11)
    return fig

def plot_correlation_heatmap(df):
    """Create correlation heatmap for key features"""
    fig, ax = plt.subplots(figsize=(10, 8))
    key_features = ['studytime', 'failures', 'absences', 'G1', 'G2', 'G3']
    corr_matrix = df[key_features].corr()
    sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
                center=0, square=True, linewidths=1, ax=ax, cbar_kws={"shrink": 0.8})
    ax.set_title('Feature Correlation Heatmap', fontsize=14, fontweight='bold')
    return fig

def plot_failures_impact(df):
    """Create bar chart showing impact of past failures"""
    fig, ax = plt.subplots(figsize=(10, 6))
    failures_mean = df.groupby('failures')['G3'].mean()
    bars = ax.bar(failures_mean.index, failures_mean.values,
                  color='coral', edgecolor='black', alpha=0.8)
    ax.set_xlabel('Number of Past Failures', fontsize=12)
    ax.set_ylabel('Average Final Grade', fontsize=12)
    ax.set_title('Impact of Past Failures on Performance', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 20)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height,
               f'{height:.1f}', ha='center', va='bottom', fontsize=10)
    return fig

def main():
    # Header
    st.title("📚 Student Academic Performance Analyzer")
    st.markdown("""
    <div style='background-color: #282A36; padding: 20px; border-radius: 10px; margin-bottom: 20px;'>
        <h4>📊 Project Information</h4>
        <p><strong>Dataset:</strong> UCI Machine Learning Repository - Student Performance Dataset</p>
        <p><strong>Course:</strong> DAI011 - Programming for AI</p>
        <p><strong>Author:</strong> Drina Musili💕- 250636DAI</p>
        <p><strong>Purpose:</strong> Analyze factors affecting student academic performance in Mathematics</p>
    </div>
    """, unsafe_allow_html=True)

    st.sidebar.header("📊 About This Application")
    st.sidebar.info("""
        **This analyzer explores:**
        - 📈 Grade distributions and statistics
        - ⏰ Study time impact on performance
        - 👥 Gender-based comparisons
        - 👨‍👩‍👧 Family support effects
        - 📉 Impact of past failures
        - 🔗 Key performance predictors

        **Dataset Details:**
        - 395 students from Portuguese schools
        - Math course performance data
        - 33 features including demographics, social factors, and grades
        """)

    st.sidebar.markdown("---")
    st.sidebar.header("🛠️ Technical Details")
    st.sidebar.markdown("""
        **Libraries Used:**
        - 🐼 Pandas - Data manipulation
        - 🔢 NumPy - Numerical operations
        - 📊 Matplotlib - Data visualization
        - 🎨 Seaborn - Statistical graphics
        - 🚀 Streamlit - Web interface
        """)

    try:
        with st.spinner('Loading dataset...'):
            df = load_data()
        st.success(f"✅ Dataset loaded successfully! ({df.shape[0]} students, {df.shape[1]} features)")
    except Exception as e:
        st.error(f"❌ Error loading data: {e}")
        st.stop()

    overall_stats = calculate_overall_stats(df)

    st.markdown("### 📊 Key Metrics Overview")
    col1, col2, col3, col4, col5 = st.columns(5)

    with col1:
        st.metric("Total Students", df.shape[0])
    with col2:
        st.metric("Average Grade", f"{overall_stats['mean']:.2f}/20")
    with col3:
        st.metric("Pass Rate", f"{overall_stats['pass_rate']:.1f}%")
    with col4:
        st.metric("Median Grade", f"{overall_stats['median']:.1f}/20")
    with col5:
        st.metric("Std Deviation", f"{overall_stats['std']:.2f}")

    st.markdown("---")

    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📋 Data Overview",
        "📈 Statistical Analysis",
        "📊 Visualizations",
        "💡 Key Insights",
        "🔍 Data Explorer"
    ])

    with tab1:
        st.header("📋 Dataset Overview")
        st.subheader("Sample Data (First 10 Rows)")
        st.dataframe(df.head(10), use_container_width=True, height=400)

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("📊 Dataset Structure")
            st.write(f"**Total Rows:** {df.shape[0]}")
            st.write(f"**Total Columns:** {df.shape[1]}")
            st.write(f"**Memory Usage:** {df.memory_usage(deep=True).sum() / 1024:.2f} KB")

            st.subheader("✅ Data Quality")
            missing = df.isnull().sum().sum()
            if missing == 0:
                st.success("✅ No missing values found - Clean dataset!")
            else:
                st.warning(f"⚠️ {missing} missing values detected")

            duplicates = df.duplicated().sum()
            if duplicates == 0:
                st.success("✅ No duplicate rows found")
            else:
                st.warning(f"⚠️ {duplicates} duplicate rows detected")

        with col2:
            st.subheader("📝 Column Information")
            info_df = pd.DataFrame({
                'Column': df.columns[:15],
                'Type': df.dtypes[:15].astype(str),
                'Non-Null': df.count()[:15].values
            })
            st.dataframe(info_df, use_container_width=True, height=400)

        st.subheader("📖 Key Features Description")
        col1_feat, col2_feat, col3_feat = st.columns(3)

        with col1_feat:
            st.markdown("""
            **Demographic Features:**
            - `age`: Student's age (15-22)
            - `sex`: Student's gender (F/M)
            - `address`: Home address type (U=urban, R=rural)
            - `famsize`: Family size (LE3 or GT3)
            """)

        with col2_feat:
            st.markdown("""
            **Academic Features:**
            - `studytime`: Weekly study time (1-4 scale)
            - `failures`: Number of past failures (0-4)
            - `absences`: Number of school absences
            - `G1, G2, G3`: Period grades (0-20)
            """)

        with col3_feat:
            st.markdown("""
            **Social Features:**
            - `famsup`: Family educational support (yes/no)
            - `activities`: Extra-curricular activities (yes/no)
            - `freetime`: Free time after school (1-5)
            - `goout`: Going out with friends (1-5)
            """)

    with tab2:
        st.header("📈 Statistical Analysis")

        st.subheader("1️⃣ Overall Grade Statistics")
        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Mean Grade", f"{overall_stats['mean']:.2f}/20",
                     help="Average final grade across all students")
            st.metric("Median Grade", f"{overall_stats['median']:.2f}/20",
                     help="Middle value when grades are sorted")

        with col2:
            st.metric("Standard Deviation", f"{overall_stats['std']:.2f}",
                     help="Measure of grade variability")
            st.metric("Grade Range", f"{overall_stats['min']} - {overall_stats['max']}",
                     help="Minimum and maximum grades")

        with col3:
            st.metric("Pass Rate", f"{overall_stats['pass_rate']:.1f}%",
                     delta=f"{overall_stats['pass_rate'] - 50:.1f}% vs 50%",
                     delta_color="inverse",
                     help="Percentage of students with grade ≥ 10")
            st.metric("Fail Rate", f"{overall_stats['fail_rate']:.1f}%",
                     delta=f"{50 - overall_stats['fail_rate']:.1f}% vs 50%",
                     delta_color="inverse",
                     help="Percentage of students with grade < 10")

        st.markdown("---")

        st.subheader("2️⃣ Performance Category Distribution")
        category_counts = df['performance_category'].value_counts()
        category_df = pd.DataFrame({
            'Category': category_counts
